# The name of GitHub Actions.
name: Pre Push Checks

# Specifies the trigger for this workflow.
on:
  push:
  pull_request:
    branches:
      - develop

# Groups together all the jobs that run in the pre-push workflow.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        # This is an action that checks out your repository onto the runner,
        # allowing you to run scripts or other actions against your code (such as build and test tools).
        uses: actions/checkout@v3
      - name: Setup Java
        # Setup Java for our repository.
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Project
        # Build release apk file.
        run: ./gradlew assemble
      - name: Run unit test
        # Run unit tests.
        run: ./gradlew test
      - name: Run Instrumented test
        # Run instrumented test(UI tests).
        run: ./gradlew connectedAndroidTest