# The name of GitHub Actions.
name: Pre Merge Checks

# Specifies the trigger for this workflow.
on:
  push:
  pull_request:
    branches:
      - develop
      - main

# Groups together all the jobs that run in the pre-push workflow.
jobs:
  ktlint-check:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        # This is an action that checks out your repository onto the runner,
        # allowing you to run scripts or other actions against your code (such as build and test tools).
        uses: actions/checkout@v3
      - name: Setup Java
        # Setup Java for our repository.
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Ktlint check
        # Run ktlint check
        run: ./gradlew ktlintCheck
  detekt-check:
    needs: ktlint-check
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        # This is an action that checks out your repository onto the runner,
        # allowing you to run scripts or other actions against your code (such as build and test tools).
        uses: actions/checkout@v3
      - name: Setup Java
        # Setup Java for our repository.
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Detekt check
        # Run detekt check
        run: ./gradlew detekt
  build:
    needs: detekt-check
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        # This is an action that checks out your repository onto the runner,
        # allowing you to run scripts or other actions against your code (such as build and test tools).
        uses: actions/checkout@v3
      - name: Setup Java
        # Setup Java for our repository.
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle
        # Build project.
        run: ./gradlew build
  unit-tests:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        # This is an action that checks out your repository onto the runner,
        # allowing you to run scripts or other actions against your code (such as build and test tools).
        uses: actions/checkout@v3
      - name: Setup Java
        # Setup Java for our repository.
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Unit Tests
        # Run unit tests.
        run: ./gradlew test
  ui-tests:
    needs: unit-tests
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        # This is an action that checks out your repository onto the runner,
        # allowing you to run scripts or other actions against your code (such as build and test tools).
        uses: actions/checkout@v3
      - name: Setup Java
        # Setup Java for our repository.
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Instrumented Tests
        # Run instrumented test(UI tests).
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck